[package]
name = "date-balance"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
electrum-client = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
sha2 = "0.10"
bitcoin = "0.32.5"
bs58 = "0.5.1"
